using m0.Foundation;
using m0.Store.FileSystem;
using m0.ZeroTypes;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace m0.Bootstrap
{
    public class CommandLineExecution
    {
        static IVertex root = MinusZero.Instance.root;
        static IVertex file_meta = root.Get(false, @"System\Meta\Store\FileSystem\File");

        public static void RunUser(string username)
        {

        }

        public static void CreateUser_BeforeInitialisation(string userName) 
        { 
            string filename = $"home-{userName}.m0j";
            string filePath = Path.Combine(MinusZero.Instance.m0DllPath, filename);

            if (File.Exists(filePath))
                File.Delete(filePath);
        }

        public static void CreateUser(string userName)
        {
            string filename = $"home{userName}.m0j";

            IVertex start = root.Get(false, @"Start:");
         
            IVertex fileVertex = start.AddVertex(file_meta, filename);

         //   IVertex store = fileVertex.Get(false, "$Store:");

         //   CreateUser_internal(store, userName);
        }

        static void CreateUser_internal(IVertex baseVertex, string userName)
        {
            IVertex Root = MinusZero.Instance.Root;

            IVertex sm = Root.Get(false, @"System\Meta");
            IVertex smzt = Root.Get(false, @"System\Meta\ZeroTypes");
            IVertex smzu = Root.Get(false, @"System\Meta\ZeroTypes\User");

            IVertex user = baseVertex.AddVertex(smzu, userName);

            IVertex Settings_meta = smzu.Get(false, @"Settings");
            IVertex CopyOnDragAndDrop_meta = Settings_meta.Get(false, @"CopyOnDragAndDrop");
            IVertex AllowManyUXItemsWithSameBaseEdgeTo_meta = Settings_meta.Get(false, @"AllowManyUXItemsWithSameBaseEdgeTo");
            IVertex AutogenerateDiagramImages_meta = Settings_meta.Get(false, @"AutogenerateDiagramImages");
            IVertex QueriesRoot_meta = smzu.Get(false, @"QueriesRoot");

            IVertex settingsVertex = user.AddVertex(Settings_meta, null);

            settingsVertex.AddVertex(CopyOnDragAndDrop_meta, "False");
            settingsVertex.AddVertex(AllowManyUXItemsWithSameBaseEdgeTo_meta, "True");
            settingsVertex.AddVertex(AutogenerateDiagramImages_meta, "True");
            settingsVertex.AddVertex(QueriesRoot_meta, null);

            user.Get(false, "Settings:").AddEdge(sm.Get(false, "?AllowBlankAreaDragAndDrop"), sm.Get(false, @"ZeroTypes\User\AllowBlankAreaDragAndDropEnum\StartAndEnd"));

            user.AddEdge(sm.Get(false, @"?$Is"), smzu);
            user.Get(false, "Settings:").AddEdge(sm.Get(false, @"?$Is"), smzu.Get(false, @"Settings"));

            user.AddEdge(smzt.Get(false, @"User\User\DefaultFormalTextLanguage"), Root.Get(false, @"System\FormalTextLanguage\ZeroCode"));

            IVertex session = VertexOperations.AddInstance(user, sm.Get(false, @"ZeroTypes\User\Session"));

            user.AddEdge(smzt.Get(false, @"User\User\CurrentSession"), session);
        }


    }
}
