using m0.Foundation;
using m0.Graph;
using m0.Store.FileSystem;
using m0.Util;
using m0.ZeroTypes;
using Microsoft.Extensions.Hosting;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace m0.Bootstrap
{
    public class CommandLineExecution
    {
        static IVertex root = MinusZero.Instance.root;
        static IVertex file_meta = root.Get(false, @"System\Meta\Store\FileSystem\File");

        static string GetFilePath(string userName)
        {
            string filename = $"home-{userName}.m0j";
            string filePath = Path.Combine(MinusZero.Instance.ApplicationPath, filename);

            return filePath;
        }

        static string GetFileName(string userName)
        {
            return $"home-{userName}.m0j";                        
        }

        public static void RunUser_BeforeInitialisation(string userName)
        {
            string filePath = GetFilePath(userName);

            bool fileDoesExist = File.Exists(filePath);
            bool fileIsEmpty = fileDoesExist && new FileInfo(filePath).Length == 0;

            if (fileDoesExist && fileIsEmpty)
                File.Delete(filePath);
        }

        public static void RunUser(string userName, bool createIfNotExist)
        {
            string filePath = GetFilePath(userName);

            bool fileDoesNotExist = !File.Exists(filePath);
            bool fileIsEmpty = !fileDoesNotExist && new FileInfo(filePath).Length == 0;

            if (createIfNotExist && (fileDoesNotExist || fileIsEmpty))
                CreateUser(userName);

            if (!File.Exists(filePath))
            {
                UserInteractionUtil.ShowException("CommandLineExecution", $"User {userName} not found.", ExceptionLevelEnum.Fatal);
                MinusZero.Instance.Fatal();
            }
            

            IVertex startVertex = GraphUtil.GetQueryOutFirst(root, "Start", null);
            IVertex homeFileVertex = GraphUtil.GetQueryOutFirst(startVertex, "File", GetFileName(userName));
            IVertex homeVertex = GraphUtil.GetQueryOutFirst(homeFileVertex, "$Store", null);

            root.AddEdge(root.Get(false, @"System\Meta\Base\Home"), homeVertex);

            IVertex currentUser = GraphUtil.GetQueryOutFirst(homeVertex, "CurrentUser", null);
            IVertex defaultFormalTextLanguage = GraphUtil.GetQueryOutFirst(currentUser, "DefaultFormalTextLanguage", null);

            MinusZero.Instance._DefaultFormalTextLanguage = defaultFormalTextLanguage;
        }

        public static void CreateUser_BeforeInitialisation(string userName) 
        { 
            string filePath = GetFilePath(userName);

            if (File.Exists(filePath))
                File.Delete(filePath);
        }        

        public static void CreateUser(string userName)
        {
            string filename = $"home-{userName}.m0j";

            IVertex start = root.Get(false, @"Start:");
         
            IVertex fileVertex = start.AddVertex(file_meta, filename);

            IVertex store = fileVertex.Get(false, "$Store:");

            CreateUser_internal(store, userName);
        }

        static void CreateUser_internal(IVertex baseVertex, string userName)
        {
            IVertex Root = MinusZero.Instance.Root;

            IVertex sm = Root.Get(false, @"System\Meta");
            IVertex smzt = Root.Get(false, @"System\Meta\ZeroTypes");
            IVertex smzu = Root.Get(false, @"System\Meta\ZeroTypes\User");            

            IVertex CurrentUser_meta = smzu.Get(false, "CurrentUser");
            IVertex User_meta = smzu.Get(false, "User");
            IVertex Settings_meta = smzu.Get(false, @"Settings");
            IVertex CopyOnDragAndDrop_meta = Settings_meta.Get(false, @"CopyOnDragAndDrop");
            IVertex AllowManyUXItemsWithSameBaseEdgeTo_meta = Settings_meta.Get(false, @"AllowManyUXItemsWithSameBaseEdgeTo");
            IVertex AllowBlankAreaDragAndDrop_meta = Settings_meta.Get(false, @"AllowBlankAreaDragAndDrop");
            IVertex AutogenerateDiagramImages_meta = Settings_meta.Get(false, @"AutogenerateDiagramImages");
            IVertex QueriesRoot_meta = smzu.Get(false, @"User\QueriesRoot");
            IVertex Is_meta = MinusZero.Instance.Is;

            IVertex user = baseVertex.AddVertex(CurrentUser_meta, userName);

            IVertex settingsVertex = user.AddVertex(Settings_meta, null);

            settingsVertex.AddVertex(CopyOnDragAndDrop_meta, "False");
            settingsVertex.AddVertex(AllowManyUXItemsWithSameBaseEdgeTo_meta, "True");
            settingsVertex.AddVertex(AutogenerateDiagramImages_meta, "True");

            user.AddVertex(QueriesRoot_meta, null);

            user.Get(false, "Settings:").AddEdge(AllowBlankAreaDragAndDrop_meta, sm.Get(false, @"ZeroTypes\User\AllowBlankAreaDragAndDropEnum\StartAndEnd"));

            user.AddEdge(Is_meta, User_meta);
            user.Get(false, "Settings:").AddEdge(Is_meta, smzu.Get(false, @"Settings"));

            user.AddEdge(smzt.Get(false, @"User\User\DefaultFormalTextLanguage"), Root.Get(false, @"System\FormalTextLanguage\ZeroCode"));

            IVertex session = VertexOperations.AddInstance(user, sm.Get(false, @"ZeroTypes\User\Session"));

            user.AddEdge(smzt.Get(false, @"User\User\CurrentSession"), session);
        }


    }
}
