# BASE

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 80

# BUILD

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["m0_console/m0_console.csproj", "m0_console/"]
COPY ["m0/m0.csproj", "m0/"]
RUN dotnet restore "./m0_console/m0_console.csproj"
COPY . .
WORKDIR "/src/m0_console"
RUN dotnet build "./m0_console.csproj" -c $BUILD_CONFIGURATION -o /app/build

# PUBLISH

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./m0_console.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# FINAL

FROM base AS final
USER root
WORKDIR /app
COPY --from=publish /app/publish .
COPY _docker_bin/ .
RUN mkdir -p /app/log && chmod -R 777 /app/log
ENV ASPNETCORE_URLS=http://0.0.0.0:80
ENTRYPOINT ["tail", "-f", "/dev/null"]